apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - celery-deploy.yaml
  - configmap.yaml
  - distritask-monitor.yaml
  - mysql-deploy.yaml
  - mysql-exporter-deployment.yaml
  - mysql-monitor.yaml
  - namespace.yaml
  - pvc.yaml
  - redis-deploy.yaml
  - redis-service.yaml
  - secret.yaml
  - sql-service.yaml
  - web-deploy.yaml
  - web-service.yaml
  - rules/telegram-alertmanager.yaml
  - rules/mysql-rule.yaml
  - rules/django-web-rules.yaml
  - rules/telegram-secret.yaml

images:
  - name: ahmedr0001/distritask
    newName: ahmedr0001/distritask
    newTag: v7
