apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./mysql-monitor.yaml
- ./redis-service.yaml
- ./web-deploy.yaml
- ./configmap.yaml
- ./celery-deploy.yaml
- ./namespace.yaml
- ./secret.yaml
- ./sql-service.yaml
- ./mysql-exporter-deployment.yaml
- ./web-service.yaml
- ./redis-deploy.yaml
- ./mysql-deploy.yaml
- ./distritask-monitor.yaml
- ./pvc.yaml
- ./rules/telegram-alertmanager.yaml
- ./rules/mysql-rule.yaml
- ./rules/django-web-rules.yaml
- ./rules/telegram-secret.yaml
