apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: distritask
data:
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_ROOT_PASSWORD: bXlyb290cGFzc3dvcmQ=
stringData:
  .my.cnf: |
    [client]
    user=exporter
    password=StrongPassword123!
    host=mysql-service
    port=3306
