apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: distritask
  labels:
    app: web-deploy
spec:
  type: NodePort
  selector:
    app: web-deploy 
  ports:
    - name: web      
      port: 8000
      targetPort: 8000
      nodePort: 32415
