# Generated by Django 5.1.6 on 2025-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
