# Generated by Django 5.1.6 on 2025-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_reached',
            field=models.BooleanField(default=False),
        ),
    ]
