# Generated by Django 5.0.6 on 2025-06-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
